In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
df = pd.read_csv("Downloads/data_science_job.csv")

In [42]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0.0

In [43]:
df.nunique()

enrollee_id               19158
city                        123
city_development_index       93
gender                        3
relevent_experience           2
enrolled_university           3
education_level               5
major_discipline              6
experience                   21
company_size                  8
company_type                  6
training_hours              241
target                        2
dtype: int64

In [44]:
df.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

In [45]:
new_df = df.drop(columns=['enrollee_id','city'])

In [46]:
new_df

,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
3,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1.0
4,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
19153,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1.0
19154,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1.0
19155,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0.0
19156,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0.0
19157,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0.0

In [47]:
new_df.describe()

       city_development_index    experience  training_hours        target
count            18679.000000  19093.000000    18392.000000  19158.000000
mean                 0.828951      9.928036       65.185787      0.249348
std                  0.123334      6.505268       59.885626      0.432647
min                  0.448000      0.000000        1.000000      0.000000
25%                  0.740000      4.000000       23.000000      0.000000
50%                  0.903000      9.000000       47.000000      0.000000
75%                  0.920000     16.000000       88.000000      0.000000
max                  0.949000     20.000000      336.000000      1.000000

In [48]:
new_df['training_hours']

0         36.0
1         47.0
2         83.0
3         52.0
4          8.0
         ...
19153     42.0
19154     52.0
19155     44.0
19156     97.0
19157    127.0
Name: training_hours, Length: 19158, dtype: float64

In [49]:
upper_limit = new_df['training_hours'].mean() + new_df['training_hours'].std()
lower_limit = new_df['training_hours'].mean() - new_df['training_hours'].std()

In [50]:
print(upper_limit)
print(lower_limit)

125.07141323192353
5.300161365727618

In [51]:
new_df['training_hours'] = np.where(
    new_df['training_hours']>upper_limit,
    upper_limit,
    np.where(
        new_df['training_hours']<lower_limit,
        lower_limit,
        new_df['training_hours']
    )
)

In [52]:
new_df.describe()

       city_development_index    experience  training_hours        target
count            18679.000000  19093.000000    18392.000000  19158.000000
mean                 0.828951      9.928036       56.850875      0.249348
std                  0.123334      6.505268       39.452422      0.432647
min                  0.448000      0.000000        5.300161      0.000000
25%                  0.740000      4.000000       23.000000      0.000000
50%                  0.903000      9.000000       47.000000      0.000000
75%                  0.920000     16.000000       88.000000      0.000000
max                  0.949000     20.000000      125.071413      1.000000

In [53]:
# Complete case analysis 
cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0]
cols

['city_development_index',
 'enrolled_university',
 'education_level',
 'experience',
 'training_hours']

In [54]:
len(df[cols].dropna()) / len(df)

0.8968577095730244

In [55]:
df_cca = df[cols].dropna()
df.shape, df_cca.shape

((19158, 13), (17182, 5))

In [57]:
df_cca.isnull().mean()

city_development_index    0.0
enrolled_university       0.0
education_level           0.0
experience                0.0
training_hours            0.0
dtype: float64

In [65]:
df_cca = df.dropna(subset=cols)
print(df_cca.shape)  
print(df.shape)

(17182, 13)
(19158, 13)

In [66]:
df_cca

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0.0
5,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11.0,NaN,NaN,24.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0.0

In [ ]:
# OneHotEncoding : gender, relevent_experience, major_discipline, company_type, enrolled_university,
# OrdinalEncoding : education_level

In [69]:
df_cca.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     0.000000
gender                    22.541031
relevent_experience        0.000000
enrolled_university        0.000000
education_level            0.000000
major_discipline          12.530555
experience                 0.000000
company_size              29.786986
company_type              30.799674
training_hours             0.000000
target                     0.000000
dtype: float64

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [71]:
# target split
X = df_cca.drop(columns=['target'])
y = df_cca['target']

In [72]:
# columns
onehot_cols = [
    'gender',
    'relevent_experience',
    'major_discipline',
    'company_type',
    'enrolled_university'
]

ordinal_cols = ['education_level']

numeric_cols = [
    'city_development_index',
    'experience',
    'training_hours'
]

In [73]:
# order matters: low to high education
education_order = [
    'Primary School',
    'High School',
    'Graduate',
    'Masters',
    'Phd'
]

In [74]:
numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
onehot_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
ordinal_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ordinal', OrdinalEncoder(
        categories=[education_order],
        handle_unknown='use_encoded_value',
        unknown_value=-1
    ))
])

In [77]:
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_pipeline, numeric_cols),
    ('onehot', onehot_pipeline, onehot_cols),
    ('ordinal', ordinal_pipeline, ordinal_cols)
], remainder='drop')
X_processed = preprocessor.fit_transform(X)
onehot_feature_names = preprocessor.named_transformers_['onehot']\
    .named_steps['onehot']\
    .get_feature_names_out(onehot_cols)

final_columns = list(numeric_cols) + list(onehot_feature_names) + ordinal_cols

In [79]:
X_processed_df = pd.DataFrame(
    X_processed,
    columns=final_columns,
    index=X.index
)

X_processed_df.head()
X_processed_df.isnull().sum()

city_development_index                         0
experience                                     0
training_hours                                 0
gender_Female                                  0
gender_Male                                    0
gender_Other                                   0
relevent_experience_Has relevent experience    0
relevent_experience_No relevent experience     0
major_discipline_Arts                          0
major_discipline_Business Degree               0
major_discipline_Humanities                    0
major_discipline_No Major                      0
major_discipline_Other                         0
major_discipline_STEM                          0
company_type_Early Stage Startup               0
company_type_Funded Startup                    0
company_type_NGO                               0
company_type_Other                             0
company_type_Public Sector                     0
company_type_Pvt Ltd                           0
enrolled_university_Full time course           0
enrolled_university_Part time course           0
enrolled_university_no_enrollment              0
education_level                                0
dtype: int64

In [80]:
X_processed_df

,city_development_index,experience,training_hours,gender_Female,gender_Male,gender_Other,relevent_experience_Has relevent experience,relevent_experience_No relevent experience,major_discipline_Arts,major_discipline_Business Degree,...,company_type_Early Stage Startup,company_type_Funded Startup,company_type_NGO,company_type_Other,company_type_Public Sector,company_type_Pvt Ltd,enrolled_university_Full time course,enrolled_university_Part time course,enrolled_university_no_enrollment,education_level
0,0.727072,1.531906,-0.485892,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
1,-0.450319,0.762568,-0.301942,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
2,-1.693119,-0.776108,0.300074,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0
4,-0.523906,1.531906,-0.954127,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0
5,-0.548434,0.147098,-0.686564,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,0.383666,0.608700,-0.385556,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
19154,0.727072,0.608700,-0.218329,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
19155,0.727072,1.531906,-0.352110,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
19156,-0.237734,-1.545447,0.534191,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
19157,0.195611,-1.237711,1.035871,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [81]:
X_train, X_test, y_train, y_test = train_test_split(
    X_processed_df,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [82]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.7701483852196683

In [83]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Decision Tree Accuracy:",
      accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7820773930753564

In [84]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.7518184463194646

In [85]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

print("KNN Accuracy:",
      accuracy_score(y_test, y_pred_knn))

C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1554, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^

KNN Accuracy: 0.7556008146639511

In [87]:
models = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Decision Tree',
        'Random Forest',
        'KNN'
    ],
    
    'Accuracy': [
        accuracy_score(y_test, y_pred_lr)*100,
        accuracy_score(y_test, y_pred_dt)*100,
        accuracy_score(y_test, y_pred_rf)*100,
        accuracy_score(y_test, y_pred_knn)*100
    ]
})

models.sort_values(by='Accuracy',
                   ascending=False)

                 Model   Accuracy
1        Decision Tree  78.207739
0  Logistic Regression  77.014839
3                  KNN  75.560081
2        Random Forest  75.181845